name: Deploy Dockerfile to S3

on:
  push:
    branches:
      - main  
      
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create a Dockerfile (Optional - if not in the repo already)
      - name: Create Dockerfile
        run: |
          echo 'FROM ubuntu:latest' > Dockerfile
          echo 'RUN apt-get update && apt-get install -y nginx' >> Dockerfile
          echo 'CMD ["nginx", "-g", "daemon off;"]' >> Dockerfile

      # Step 3: Zip the Dockerfile
      - name: Zip Dockerfile
        run: |
          zip dockerfile.zip Dockerfile

      # Step 4: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired region

      # Step 5: Upload the ZIP file to S3
      - name: Upload to S3
        run: |
          aws s3 cp dockerfile.zip s3://your-bucket-name/dockerfile.zip
